language: java
jdk:
  - oraclejdk8
services:
  - mongodb
before_script:
  - mongo ousontmesaffaires --eval 'db.createUser({user:"user",pwd:"password",roles:["readWrite"]});'

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)